---

- name: Test if epel rpm exists
  shell: sudo yum repolist | grep epel
  ignore_errors: true
  register: exiting_epel_rpm_check

- name: Install epel rpm
  shell: >
    cd /tmp; 
    wget http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm;
    sleep 30;
    ls epel-release-latest-7.noarch.rpm;
    sudo yum -y install epel-release-latest-7.noarch.rpm;
    sudo yum repolist | grep epel
  when: exiting_epel_rpm_check|failed
    
- name: make sure python-pip is installed
  yum: name=python-pip state=present

- name: make sure libffi is installed
  yum: name=libffi-devel state=present

- name: make sure virtualenv is installed
  yum: name=python-virtualenv state=present

### setup venv & pip install ansible
- name: setup venv & pip install ansible
  sudo_user: stack
  pip: name=ansible virtualenv=/home/stack/venv_ansible

- name: create the ~/ansible.cfg file 
  sudo_user: stack
  template: src=ansible.cfg dest=/home/stack/.ansible.cfg

