---

- name:  Write instackenv.json
  template: src=nodes.json dest=/home/stack/instackenv.json owner=stack group=stack

- name: import nodes
  sudo_user: stack
  shell: source /home/stack/stackrc &&  openstack baremetal import --json /home/stack/instackenv.json

- name: configure boot kernals
  sudo_user: stack
  shell: sleep 20 && source /home/stack/stackrc && openstack baremetal configure boot

- name: discover nodes
  sudo_user: stack
  shell: source /home/stack/stackrc &&  openstack baremetal introspection bulk start
  when: node_discovery


- name: Check for baremetal flavor
  sudo_user: stack
  shell: source /home/stack/stackrc &&  openstack flavor list | grep -q baremetal
  ignore_errors: true
  register: flavor_baremetal_check

- name: Setup baremetal flavor
  sudo_user: stack
  shell: source /home/stack/stackrc && openstack flavor create --id auto --ram 10 --disk 40 --vcpus 1 baremetal
  when: flavor_baremetal_check|failed
  register: flavor_baremetal_create

- name: Configure baremetal flavor
  sudo_user: stack
  shell: source /home/stack/stackrc && openstack flavor set --property "cpu_arch"="x86_64" --property "capabilities:boot_option"="local" baremetal
  when: not flavor_baremetal_create|skipped

- name: Check for control flavor
  sudo_user: stack
  shell: source /home/stack/stackrc &&  openstack flavor list | grep -q control
  ignore_errors: true
  register: flavor_control_check

- name: Setup control flavor
  sudo_user: stack
  shell: >
        source /home/stack/stackrc &&
        openstack flavor create --id auto --ram 4096 --disk 40 --vcpus 1 control &&
        openstack flavor set
        --property "cpu_arch"="x86_64"
        --property "capabilities:boot_option"="local"
        --property "capabilities:profile"="control" control
  when: flavor_control_check|failed


- name: Check for compute flavor
  sudo_user: stack
  shell: source /home/stack/stackrc &&  openstack flavor list | grep -q compute
  ignore_errors: true
  register: flavor_compute_check

- name: Setup compute flavor
  sudo_user: stack
  shell: >
        source /home/stack/stackrc &&
        openstack flavor create --id auto --ram 4096 --disk 40 --vcpus 1 compute &&
        openstack flavor set --property "cpu_arch"="x86_64" --property "capabilities:boot_option"="local" --property "capabilities:profile"="compute" compute
  when: flavor_compute_check|failed


- name: Check for ceph flavor
  sudo_user: stack
  shell: source /home/stack/stackrc &&  openstack flavor list | grep -v ceph-storage | grep ceph
  ignore_errors: true
  register: flavor_ceph_check

- name: Setup ceph flavor
  sudo_user: stack
  shell: >
        source /home/stack/stackrc &&
        openstack flavor create --id auto --ram 4096 --disk 40 --vcpus 1 ceph &&
        openstack flavor set
        --property "cpu_arch"="x86_64"
        --property "capabilities:boot_option"="local"
        --property "capabilities:profile"="ceph" ceph
  when: flavor_ceph_check|failed

# NOTE: the need for this might go away with the next OSP release
- name: Set node name
  sudo_user: stack
  shell: >
        source /home/stack/stackrc &&
        ironic node-update $(/home/stack/bin/ipmi_address_to_uuid.py {{ item.pm_addr }}) add name={{ item.name | default(item.pm_addr) }}
  with_items: "{{ overcloud_nodes.nodes }}"

- name: Set node capabilities
  sudo_user: stack
  shell: >
        source /home/stack/stackrc &&
        ironic node-update $(/home/stack/bin/ipmi_address_to_uuid.py {{ item.pm_addr }}) add properties/capabilities='{{ item.capabilities }}'
  with_items: "{{ overcloud_nodes.nodes }}"
