#!/bin/sh
#
# rhcert-backend: Red Hat Hardware Test Suite
#
# chkconfig: 2345 35 98
# description: Red Hat Hardware Test Suite

. /etc/rc.d/init.d/functions
RETVAL=0
rhcert=/usr/bin/rhcert-backend

start() {
    $rhcert server daemon --debug=high &
}

stop() {
    $rhcert server stop
	killall rhcert-backend
}

reload() {
	stop
	start
}

rhcert_status() {
	$rhcert server status
	if ps ax | fgrep rhcert-backend &>/dev/null; then
		echo $"rhcert-backend is running"
		return 0
	else
		echo $"rhcert-backend is not running"
		return 3
	fi
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	status)
		rhcert_status
		RETVAL=$?
		;;
	restart)
		stop
		start
		;;
	condrestart)
		if qemu_status &>/dev/null; then
			stop
			start
		fi
		;;
	*)
		echo $"Usage: $prog {start|stop|status|restart|condrestart}"
		exit 1
esac
exit $RETVAL

