---

- name: check whether repo is already pulled 
  stat: path=/home/stack/openstack-tools
  register: dir_stat

#git: repo=http://gitlab.cisco.com/tiswanso/openstack-tools.git
- name: Untar tiswanso openstack-tools
  sudo_user: stack
  shell: tar -xzvf /home/stack/openstack-tools.tar.gz -C /home/stack
  when: not dir_stat.stat.exists
