- name: Check DHCP Agent exists
  stat: path=/etc/neutron/dhcp_agent.ini
  register: dhcp_exists

- name: Configure dnsmasq
  shell: openstack-config --set /etc/neutron/dnsmasq-neutron.conf "" dhcp-option-force 26,9000
  when: dhcp_exists.stat.exists is defined and dhcp_exists.stat.exists

- name: Configure DHCP Agent
  shell: openstack-config --set /etc/neutron/dhcp_agent.ini DEFAULT dnsmasq_config_file /etc/neutron/dnsmasq-neutron.conf
  when: dhcp_exists.stat.exists is defined and dhcp_exists.stat.exists

- name: Configure neutron.conf
  shell: openstack-config --set  /etc/neutron/neutron.conf DEFAULT network_device_mtu 9000

- name: Configure nova.conf
  shell: openstack-config --set  /etc/nova/nova.conf DEFAULT network_device_mtu 9000

- name: Restart services
  shell: systemctl restart neutron-server
  when: "'overcloud_controller' in {{ group_names }}"

- name: Restart services
  shell: systemctl restart openstack-nova-api
  when: "'overcloud_compute' in {{ group_names }}"

- name: Restart services
  shell: systemctl restart neutron-dhcp-agent
  when: "'overcloud_controller' in {{ group_names }}"