---
# Install overcloud
- hosts: "{{ director_node_ssh_ip }}"
  connection: ssh
  roles:
    - osp-overcloud
    - osp-overcloud-post
    - add-overcloud-host

#CB_DCI Turned off to run with DCI
# add custom config to the compute nodes
#- hosts: overcloud_compute
#  connection: ssh
#  roles:
#    - sysctl-bridge-conf

#CB_DCI Turned off to run with DCI
# run tests and report
#- hosts: "{{ director_node_ssh_ip }}"
#  connection: ssh
#  roles:
#    - osp-test-data
#    - read-overcloudrc-props
#    - rh-tempest
#    - scale-patch
#    - report_status
