---

# sysctl.d/99-bridge.conf is needed on compute nodes
- name: Write sysctl.d/99-bridge.conf
  sudo: true
  template: src=99-bridge.conf dest=/etc/sysctl.d/99-bridge.conf mode=644

- name: reload sysctl
  sudo: true
  shell: sysctl --system
